// wallet-access-react/src/App.tsx
import { MetamaskProvider } from '@rarimo/providers-evm'
import { useProvider } from '@rarimo/react-provider'
import { useEffect } from 'react'

function App() {
  const { provider } = useProvider(MetamaskProvider)

  useEffect(() => {
    const connectToProvider = async () => {
      await provider.connect()
    }
    if (!provider) connectToProvider()
    if (provider?.address) console.log(provider.address)
  }, [provider])

  return <div className="App">Wallet address: {provider?.address}</div>
}

export default App

// wallet-access/src/App.vue
<script setup lang="ts">
import { createProvider, ChainTypes } from '@rarimo/provider'
import { MetamaskProvider } from '@rarimo/providers-evm'

const getMetamaskWalletInfo = async () => {
  // Connect to the Metamask wallet in the browser, using the MetamaskProvider interface to limit bundle size.
  const provider = await createProvider(MetamaskProvider)
  await provider.connect()

  // Get the address of the wallet
  console.log('Address:', provider.address)
  console.log('chainType:', ChainTypes[provider.chainType!])
  console.log('providerType:', provider.providerType)
}

getMetamaskWalletInfo()
</script>

<template>
  <div>
  </div>
</template>
